version: '3.8'
services:
  db:
    image: mysql:latest
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: bank
      MYSQL_USER: bank
      MYSQL_PASSWORD: bankpwd
volumes:
  db_data: {}